#!/usr/bin/bash

HISTORY_FILE=".ptb_history"
TRAVERSED_HISTORY="$HISTORY_FILE.trav"

function handle-piping() {
	tail -f $HISTORY_FILE | while read f; do
		echo "$f" | fold -26 | while read ff; do
			if [ "$ff" == "---ENDOFCOMM---" ]; then
				am broadcast -a com.banglejs.uart.tx -e line "term.print(\"End of Communication\n\")" > /dev/null
				rm $TRAVERSED_HISTORY
				rm $HISTORY_FILE 2> /dev/null	# this WILL throw an error
				exit
			fi
			am broadcast -a com.banglejs.uart.tx -e line "term.print(\"$ff\n\")" > /dev/null
			echo "." >> $TRAVERSED_HISTORY
			lc=$(cat $TRAVERSED_HISTORY | wc -l)
			if [ $((lc % 16)) -eq 0 ]; then
				am broadcast -a com.banglejs.uart.tx -e line "load('termux.app.js')" > /dev/null
			fi
		done
	done 2> /dev/null
}

am broadcast -a com.banglejs.uart.tx -e line "load('termux.app.js')" > /dev/null
sleep 1
am broadcast -a com.banglejs.uart.tx -e line "term.print(\"New Communication\n\")" > /dev/null
sleep 1
touch $HISTORY_FILE
touch $TRAVERSED_HISTORY
handle-piping 2> /dev/null &
while read line; do
	echo "$line"
	echo "$line" >> $HISTORY_FILE
done
echo "---ENDOFCOMM---" >> $HISTORY_FILE
